### ISSUE TITLE
ignored error in app.go

### ISSUE THREAD

**Issue by omritoptix** [dymensionxyz/rollapp-wasm#71]
In `wasm:app/app.go:290`, the MAX_WASM_SIZE variable is parsed into an int32 value.
However, the error is ignored when parsing the value.

**Comment by trinitys7** [comment]
the MAX_WASM_SIZE seems not worked well and we added a flag to parse it in cmd/start.go, so that we can use like this:
`rollapp-wasm start --max-label-size 64 --max-wasm-size 2048000 --max-wasm-proposal-size 2048000`
